In [1]:
from scipy.stats import genlogistic
import pandas as pd
import pickle
import numpy as np

In [1]:
release_data_path = './movie_dataset/release_dates.csv'
rdf = pd.read_csv(release_data_path, delimiter=',', header=None)
rdf.head()
zero_scores = stats.zscore(rdf[2])
refined_released_dates = rdf[2][ (np.abs(zero_scores) < 3) ]
rrd = refined_released_dates.to_numpy()

In [56]:
import shelve
data_directory_prefix = './sequence_data/synthetic_100000'
raw_sequences_data_path = data_directory_prefix + '/sequences.shv'

d = shelve.open('./test111.shv')  

In [63]:
a = list()
a.append(123)
d['123'] = a

In [66]:
import diskcache
help(diskcache)

Help on package diskcache:

NAME
    diskcache

DESCRIPTION
    DiskCache API Reference
    
    The :doc:`tutorial` provides a helpful walkthrough of most methods.

PACKAGE CONTENTS
    cli
    core
    djangocache
    fanout
    persistent
    recipes

CLASSES
    builtins.Exception(builtins.BaseException)
        diskcache.core.Timeout
    builtins.UserWarning(builtins.Warning)
        diskcache.core.EmptyDirWarning
        diskcache.core.UnknownFileWarning
    builtins.object
        diskcache.core.Cache
        diskcache.core.Disk
            diskcache.core.JSONDisk
        diskcache.fanout.FanoutCache
        diskcache.recipes.Averager
        diskcache.recipes.BoundedSemaphore
        diskcache.recipes.Lock
        diskcache.recipes.RLock
    collections.abc.MutableMapping(collections.abc.Mapping)
        diskcache.persistent.Index
    collections.abc.Sequence(collections.abc.Reversible, collections.abc.Collection)
        diskcache.persistent.Deque
    
    class Averager(built

In [22]:
d.close()

In [25]:
import pymongo
from pymongo import MongoClient
client = MongoClient()

In [28]:
db = client.test_database
import datetime

In [29]:
post = {"author": "Mike",
         "text": "My first blog post!",
         "tags": ["mongodb", "python", "pymongo"],
         "date": datetime.datetime.utcnow()}

In [48]:
post2 = {"author": "Mike2",
         "text": "My first blog post2!",
         "tags": ["mongo2db", "pyt2hon", "py2mongo"],
         "date": datetime.datetime.utcnow()}

In [30]:
posts = db.posts

In [49]:
post_id = posts.insert_one(post2).inserted_id
post_id

ObjectId('5edeff9b11c2691c9cac21c1')

In [55]:
import pprint
pprint.pprint(posts.find_one())

{'_id': ObjectId('5edefd0a11c2691c9cac21c0'),
 'author': 'Mike',
 'date': datetime.datetime(2020, 6, 9, 3, 7, 24, 82000),
 'tags': ['mongodb', 'python', 'pymongo'],
 'text': 'My first blog post!'}


In [2]:
import diskcache as dc
cache = dc.Cache('tmp')
# cache[b'key'] = b'value'
# %timeit cache[b'key'] = b'value'

In [73]:
d = shelve.open('./tmp.shv')  
d['key'] = b'value'
%timeit d['key'] = b'value'

11.9 µs ± 369 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [76]:
cache[1] = 2

In [39]:
import pandas as pd
import pickle

rating_data_path = './movie_dataset/ratings_rev1.csv'
rdf = pd.read_csv(rating_data_path, delimiter=',')

In [4]:
rdf.head()

userId  movieId  rating   timestamp
0       1      307     3.5  1256677221
1       1      481     3.5  1256677456
2       1     1091     1.5  1256677471
3       1     1257     4.5  1256677460
4       1     1449     4.5  1256677264

In [5]:
release_data_path = './movie_dataset/release_dates.csv'
redf = pd.read_csv(release_data_path, delimiter=',', header=None)

redf.head()

0           1          2
0  1  1995-10-30  814978800
1  2  1995-12-15  818953200
2  3  1995-12-22  819558000
3  4  1995-12-22  819558000
4  5  1995-12-08  818348400

In [11]:
rel_index = dict()
for i in range(len(redf)):
    rel_index[redf[0][i]] = redf[2][i]

In [40]:
print(rdf.head())
for i in range(len(rdf)):
    temp_timestamp = (rdf['timestamp'][i] - rel_index[rdf['movieId'][i]])
    if temp_timestamp > 0 :
        temp_timestamp /= 2
        rdf['timestamp'][i] = temp_timestamp + rel_index[rdf['movieId'][i]]

print(rdf.head())
#     rdf['timestamp'][i] = 
#     print(rel_index[rdf['movieId'][i]])
#     temp_timestamp 
#     if rel_index[rdf['movieId']] > temp_timestamp:
#         = temp_timestamp


   userId  movieId  rating   timestamp
0       1      307     3.5  1256677221
1       1      481     3.5  1256677456
2       1     1091     1.5  1256677471
3       1     1257     4.5  1256677460
4       1     1449     4.5  1256677264


/home/dbadmin/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


   userId  movieId  rating   timestamp
0       1      307     3.5   991634410
1       1      481     3.5  1001743328
2       1     1091     1.5   936122535
3       1     1257     4.5   877240930
4       1     1449     4.5  1048615232


In [41]:
new_rating_data_path = './movie_dataset/ratings_enhanced.csv'
rdf.to_csv(new_rating_data_path, index=False)

In [37]:
new_rdf = pd.read_csv(new_rating_data_path, delimiter=',')

In [38]:
new_rdf.head()

Unnamed: 0  userId  movieId  rating  timestamp
0           0       1      307     3.5  726591663
1           1       1      481     3.5  746809260
2           2       1     1091     1.5  615567676
3           3       1     1257     4.5  497804490
4           4       1     1449     4.5  840553249

In [5]:
import pickle
new_rating_data_path = './sequence_data/synthetic_200000/sequences.pkl'
syn_rel_data_path = './sequence_data/synthetic_200000/release_data.pkl'
syn_set_data_path = './sequence_data/synthetic_200000/set_sequences_set_16.pkl'

with open(new_rating_data_path, 'rb') as f:
    synthetic_seq = pickle.load(f)

with open(syn_rel_data_path, 'rb') as f :
    syn_rel_index = pickle.load(f)

with open(syn_set_data_path, 'rb') as f :
    synthetic_set_seq = pickle.load(f)

In [3]:
synthetic_seq[0][0], synthetic_seq[0][1]

(array([ 2521,  4530, 24486,    64, 30117, 10380, 10410, 32067, 25913,
         1201,     8,   882, 32059,  3356, 12338, 12867,     2, 25156,
         1632,  5396, 14604, 21399, 35622,  3451, 35894,  1688, 17286,
           51,  1612,  3960,  3614,  1253,    17, 24981,  5595, 11983,
        20403,  3591, 32775, 16491,  2710,  4009, 23326, 12759,  1514,
         1840, 14266,  5197, 18800,  1073,  4322,  5243,    81,    66,
        26333, 25590,  3540, 19300,  1332, 13373, 40561, 37839, 38657,
         6786,  6397,  2694,  1994,   675, 24711, 12087,  7653, 18286,
        31894,  9172,  1525,  7994,  1067,    80, 19820, 31112,   164,
         4065,    42, 37190,  2346,  7037,  1598, 25429,   659,  9564,
        14149, 21860, 31759,  1477,  5527, 12453, 12478, 34339,   371,
            3, 15809,  3137,   709,   927,  8738,  7304,   143,  7827,
          100, 28410, 40038,  8786,  6585,  1250,    59,  3179, 32163,
         1364,  8004, 22672,   125, 27443,  4154,    54,  1244, 18202,
      

In [11]:
synthetic_set_seq[0][0].max_timestamp, synthetic_set_seq[0][0].content

(-245823198,
 frozenset({8,
            64,
            882,
            1201,
            2521,
            3356,
            4530,
            10380,
            10410,
            12338,
            12867,
            24486,
            25913,
            30117,
            32059,
            32067}))

In [4]:
syn_rel_index[2521]

-932986220

In [14]:
import pickle
new_rating_data_path = './sequence_data/not_real_world/sequences.pkl'
old_rating_data_path = './sequence_data/real_world/sequences.pkl'
# syn_rel_data_path = './sequence_data/synthetic_200000/release_data.pkl'
# syn_set_data_path = './sequence_data/synthetic_200000/set_sequences_set_16.pkl'

with open(new_rating_data_path, 'rb') as f:
    new_seq = pickle.load(f)

with open(old_rating_data_path, 'rb') as f:
    old_seq = pickle.load(f)
# with open(syn_rel_data_path, 'rb') as f :
#     syn_rel_index = pickle.load(f)

# with open(syn_set_data_path, 'rb') as f :
#     synthetic_set_seq = pickle.load(f)

In [15]:
len(new_seq), len(old_seq)

(250703, 250703)

In [30]:
new_seq[3], old_seq[3]

(array([[      960,      3171,      1221,      1321,      1985,      2024,
               640,       828,      1645,      1825,      2028],
        [105181703, 299885003, 550919303, 656154503, 769252205, 815821805,
         886281005, 891724205, 911077805, 918551405, 923173805]]),
 array([[      960,       640,      1645],
        [945141407, 945141610, 945141611]]))

In [25]:
new_length_list = list(map(lambda x: len(new_seq[x][0]), new_seq.keys()))
old_length_list = list(map(lambda x: len(old_seq[x][0]), old_seq.keys()))

In [28]:
np.array(new_length_list) != np.array(old_length_list) 

array([False, False,  True, ..., False, False,  True])

In [28]:
t_array = np.array([1,2,3])
d2_array = np.array([[1,2,3],[4,5,6]])

result = np.where(t_array > 2)